walThreshold: 10
walEntriesPerFile: 10
walLowWatermark: 5
memtableThreshold: 10000
cacheSize: 100
tokenBucketInterval: 60
tokenBucketMax: 1000
hllMinPrecision: 4
hllMaxPrecision: 16
hllP: 4
cmsEpsilon: 0.01
cmsDelta: 0.01
bloomFilterExpectedElements: [ 512, 1024, 2048, 4096, 8192, 16384, 32728, 65535 ]
bloomFilterFalsePositive: 0.02
lsmMaxLevels: 8
blockSize: 16
lsmMaxArray:
  - 6
  - 6
  - 6
lsmReqArray:
  - 2
  - 2
  - 2
